<?php

namespace LouvreBundle\Repository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends \Doctrine\ORM\EntityRepository
{
	 public function getCommandesQte($jour)
    {
        return $this->_em->createQueryBuilder()
            ->select('SUM(a.quantite)')
            ->from($this->_entityName, 'a')
            ->where('a.jour = :jour')
            ->setParameter('jour', $jour)
            ->getQuery()
            ->getSingleResult()
            ;
    }

    public function getCommandeToken($token)
    {
        return $this->createQueryBuilder('c')
            ->where('c.token = :token')
            ->setParameter('token', $token)
            ->getQuery()
            ->getSingleResult()
            ;

    }
}
